# add objects referenced by the test function headers
OBJS += test/connection.o test/distribution_metadata.o test/extend_ddl_commands.o \
		test/fake_fdw.o test/generate_ddl_commands.o test/create_shards.o \
		test/prune_shard_list.o test/test_helper_functions.o
