language: c
cache: apt
env:
  global:
    - enable_coverage=yes
    - PG_PRELOAD=pg_shard
  matrix:
    - PGVERSION=9.3
    - PGVERSION=9.4
    - PGVERSION=9.5
before_install:
  - git clone -b v0.1.0 --depth 1 https://github.com/citusdata/tools.git
  - tools/travis/setup_apt.sh
  - tools/travis/nuke_pg.sh
install:
  - sudo pip install cpp-coveralls
  - tools/travis/install_pg.sh
  - tools/travis/install_citus.sh
before_script: tools/travis/config_and_start_cluster.sh
script: tools/travis/pg_travis_test.sh
after_success:
  - sudo chmod 666 *.gcda
  - coveralls --exclude test/include --exclude test/src --exclude src/ruleutils_93.c --exclude src/ruleutils_94.c --exclude src/ruleutils_95.c --gcov-options '\-lp'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/citusdb_pkgs
